FROM nginx
MAINTAINER Waleed Samy <waleed_samy@ymail.com>

# Copy ubissl to root folder
COPY ubissl /root/ubissl

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf